### ISSUE TITLE
Apple FR - Custom - v2.klc  404: Not Found

### ISSUE THREAD

**Issue by habibmbacfou** [MilesTEG1/Majuscules_Accentuees_clavier_Windows#1]
Merci pour ce tuto détaillé.
Le téléchargement du fichier Apple FR - Custom - v2.klc est impossible et j'ai l'erreur 404: Not Found. Pouvez-vous svp charger le bon fichier ?

**Comment by MilesTEG1** [comment]
Bonjour,
Comment essayer-vous de télécharger le fichier ?
Car je viens d'essayer et le fichier est bien disponible...
![image](https://user-images.githubusercontent.com/29298312/138217031-a7ecec1e-d15c-419a-988c-a598d066abb3.png)

Il faut cliquer sur le bouton raw, et enregistrer sous la page qui s'affichera :
https://raw.githubusercontent.com/MilesTEG1/Majuscules_Accentuees_clavier_Windows/main/KLC_files/Apple%20FR%20-%20Custom%20-%20v2.klc

**Comment by habibmbacfou** [comment]
Ce nouveau lien fonctionne merci
